Repository GoogleCloudPlatform/compute-daisy, pull requests merged in 2022-02, with the labels that each got.

#5 Add function docs to fix lint errors
  workflow.go
Labels: size/XS

#6 Fix template for e2e tests
  daisy_integration_tests/daisy_e2e.test.gotmpl
Labels: size/XS, lgtm

#10 Add OWNERS file
  OWNERS
Labels: lgtm, size/S

#8 Implement build in Dockerfile
  Dockerfile
Labels: lgtm, size/M, approved

#11 consider paths in OUTS as valid
  image.go
Labels: size/XS, lgtm, approved

#9 machine image dependency: move from Beta to GA
  compute/compute.go
  compute/compute_test.go
  compute/test_client.go
  compute/test_client_test.go
  go.mod
  go.sum
  instance.go
  machineimage.go
  machineimage_test.go
  step_create_machine_images_test.go
  test_common_test.go
  workflow_test.go
Labels: lgtm, size/L, approved

#12 Fix paths in daisy_test_runner
  daisy_test_runner.Dockerfile
Labels: size/XS, lgtm, approved
