Repository GoogleCloudPlatform/compute-daisy, pull requests merged in 2023-06, with the labels that each got.

#25 Update daisy build
  Dockerfile
  daisy_test_runner.Dockerfile
  image.go
  workflow.go
Labels: lgtm, size/S, approved

#26 go: update golang to 1.17
  go.mod
  go.sum
Labels: lgtm, size/S, approved

#28 Use golang bullseye images instead of 1.19-bullseye.
  Dockerfile
  daisy_test_runner.Dockerfile
Labels: size/XS, lgtm, approved

#27 Change some tests and go mod
  go.mod
  go.sum
  step_start_instances_test.go
  step_stop_instances_test.go
  step_wait_for_instances_signal_test.go
  test_common_test.go
Labels: lgtm, approved, size/XL
